import Height_map as hm
import math
#MAP data
X_SIZE = 84
Y_SIZE = 64
BRUSH_DIAMETER = 30
BRUSH_DECREMENT = 3

MAP = hm.Heightmap(X_SIZE, Y_SIZE, 0)
brush = hm.Brush(BRUSH_DIAMETER)
brush.Gaussian(BRUSH_DECREMENT)
#MAP.stampsOnMap([],brush)

#DEBUGING
PLOT_ENABLE = True

#ALGORITHM

HILL_CLIMB    = False
ANNELING_RUN  = not HILL_CLIMB

#Anneling
ITERATIONS = 5000
TEMPERATURE_INIT = 40
TEMPERATURE_MIN = .01

#ALPHA = 0.996317916103
ALPHA = math.exp(math.log(TEMPERATURE_MIN/TEMPERATURE_INIT)/ITERATIONS)


#40*ALPHA^1000 = 1
#Isolate ALPHA


#A* MACROBLOCK
