import Height_map as hm

#MAP data
X_SIZE = 84
Y_SIZE = 64
BRUSH_DIAMETER = 30
BRUSH_DECREMENT = 3

MAP = hm.Heightmap(X_SIZE, Y_SIZE, 0)
brush = hm.Brush(BRUSH_DIAMETER)
brush.Gaussian(BRUSH_DECREMENT)
#MAP.stampsOnMap([],brush)

#DEBUGING
PLOT_ENABLE = True

#ALGORITHM

HILL_CLIMB    = False
ANNELING_RUN  = not HILL_CLIMB

#Anneling
ITERATIONS = 1000
TEMPERATURE_INIT = 4000
ALPHA = .96